//! Secrets provider abstraction (W20β-3 / ADR-052).
//!
//! `arcgraph-core` ships a `SecretsProvider` trait + two
//! implementations:
//!
//! - `OsKeyringProvider` — production default; wraps the `keyring`
//!   crate's macOS Keychain / Windows Credential Manager / Linux
//!   Secret Service backends. Feature-gated behind `os-keyring` so
//!   headless CI environments build without D-Bus / Secret Service.
//! - [`EnvSecretsProvider`] — development-only; reads from process env
//!   vars (`ARCGRAPH_SECRET_<KEY>`). Construction emits a
//!   `tracing::warn!` tagged `unsafe_for_prod=true` so operators see
//!   the danger in startup logs (pinned by tests).
//!
//! Full KMS providers (HashiCorp Vault, AWS KMS, GCP KMS, Azure Key
//! Vault) are **deferred to v1.2** per sister ADR-051. The trait
//! surface is stable at v1.0; new impls add via the `dyn` interface.
//!
//! ## Threat model
//!
//! See ADR-052 §"Context" for the full threat model. In short: cold
//! disk theft, backup leakage, and snapshot exfiltration. Chosen-
//! plaintext / chosen-ciphertext active attackers are NOT in the v1.0
//! threat model (those land at v1.2 with HSM / KMS lift per ADR-051).
//!
//! ## Why a 32-byte fixed-width [`SecretValue`]
//!
//! Every consumer of the provider in v1.0-α is an AES-256 key (32
//! bytes). Fixing the width at the trait surface simplifies key
//! rotation (`rotate()` returns a new 32-byte key generated by the
//! provider; no caller-side size negotiation), eliminates variable-
//! length attack surface (no length-extension or oracle attacks on
//! the provider's storage layer), and matches the FIPS-140-3
//! candidate AES-256-GCM requirement. v1.1+ consumers (e.g.,
//! per-tenant Curve25519 keys for signing) will need a
//! variable-width sibling type; the trait MAY add a sibling method
//! at v1.1 — adding methods to a trait is a breaking change but the
//! existing `get` / `set` / `rotate` / `delete` shape stays.
//!
//! ## See also
//!
//! - `arcgraph-storage::encryption` — the production consumer of this trait
//! - protocol adapters — per-tenant credential storage

pub mod env;
pub mod error;
#[cfg(feature = "os-keyring")]
pub mod keyring;
// ADR-216 §D-1: the key-MANAGEMENT abstraction (KeySource trait + the
// on-disk envelope types). Layered ABOVE `SecretsProvider` (the
// key-STORAGE backend). The ONE v1 concrete source
// (`SecretsProviderKeySource`) lives in `arcgraph-storage::encryption`
// (it performs the AES-256-GCM wrap via the storage-owned cipher; core
// carries no `aws-lc-rs` dep) — only the trait + types live here.
pub mod keysource;
pub mod value;

pub use env::EnvSecretsProvider;
pub use error::SecretsError;
#[cfg(feature = "os-keyring")]
pub use keyring::OsKeyringProvider;
pub use keysource::{
    ENCRYPTION_KEY_NAMESPACE_WAL, KekVersion, KeyScope, KeySource, KeySourceError, WrapAlg,
    WrappedDek,
};
pub use value::{KeyVersion, SECRET_VALUE_LEN, SecretValue};

/// The provider trait every secrets backend implements.
///
/// All methods are synchronous and `&self`-callable so the trait is
/// `Send + Sync` and embeddable as `Arc<dyn SecretsProvider>` in
/// long-lived structs (WAL encryption config, page-store encryption
/// adapter, connector credential store).
///
/// **Key namespace convention** (v1.0-α): callers prefix keys with a
/// per-subsystem namespace + per-tenant scope + version suffix —
/// e.g., `arcgraph.wal.encryption_key.v1`,
/// `connector.credentials.t<tenant>.v<version>`. The provider treats
/// the entire string as opaque; the convention is enforced at the
/// consumer (see `arcgraph-storage::encryption::wal::WalEncryption`).
///
/// **Threading contract**: methods MAY block on the underlying
/// keyring / D-Bus / file IO. Callers SHOULD invoke from a non-hot-
/// path thread (typical: at startup + at rotation events).
pub trait SecretsProvider: Send + Sync + std::fmt::Debug {
    /// Retrieve the secret bound to `key`. Returns
    /// [`SecretsError::NotFound`] if no such binding exists.
    fn get(&self, key: &str) -> Result<SecretValue, SecretsError>;

    /// Bind `value` to `key`, overwriting any prior value.
    fn set(&self, key: &str, value: SecretValue) -> Result<(), SecretsError>;

    /// Rotate the key bound to `key`: generate a fresh 32-byte value,
    /// increment the per-key version counter, and store the new value
    /// at `key.v<new_version>`. Returns the new [`KeyVersion`].
    ///
    /// Historical versions remain accessible at `key.v<N>` for N <
    /// new_version — the provider does NOT delete prior versions
    /// (operator policy decides retention). Callers that need
    /// version-aware reads (e.g., per-record WAL decryption) read
    /// `key.v<N>` explicitly via [`Self::get`].
    fn rotate(&self, key: &str) -> Result<KeyVersion, SecretsError>;

    /// Delete the secret bound to `key`. Returns
    /// [`SecretsError::NotFound`] if no such binding exists; idempotent
    /// re-delete is the caller's responsibility (wrap with a
    /// `match err { NotFound => Ok(()), other => other }` if
    /// idempotency is needed).
    fn delete(&self, key: &str) -> Result<(), SecretsError>;
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Compile-time pin: `dyn SecretsProvider` is object-safe + Send +
    /// Sync. Without `Send + Sync` the WAL encryption config (which
    /// holds an `Arc<dyn SecretsProvider>`) would not compile against
    /// the writer thread's `move` semantics.
    #[test]
    fn provider_is_object_safe_and_send_sync() {
        fn assert_object_safe(_: &dyn SecretsProvider) {}
        fn assert_send_sync<T: Send + Sync>() {}
        let p = EnvSecretsProvider::with_prefix("test_object_safe");
        assert_object_safe(&p);
        assert_send_sync::<EnvSecretsProvider>();
    }
}
