apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "arcgraph.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "arcgraph.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.env }}
  {{- if $value }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
