//! Plan-cache key derivation — parameter / literal canonicalization.
//!
//! # Cache key shape (per ADR-038 amendment-03 §TIER-2-a)
//!
//! `(tenant_id, parameter-erased AST, parameter-type signature)`. Two
//! queries that differ ONLY in inline literal values or parameter
//! values MUST share a cache entry — they have the same plan tree
//! shape. This module derives the cache key from a parsed
//! [`crate::ast::Statement`] by:
//!
//! 1. **Cloning** the statement and walking the clone in-place,
//!    replacing every literal-value-bearing slot
//!    ([`crate::ast::Literal::Integer`] / [`crate::ast::Literal::Float`]
//!    / [`crate::ast::Literal::String`] / [`crate::ast::Literal::Bool`])
//!    with a kind-preserving zero placeholder
//!    (`Integer(0)` / `Float(0.0)` / `String("")` / `Bool(false)`),
//!    and replacing every [`crate::ast::Expression::Parameter`] with
//!    a canonical name placeholder.
//! 2. **Collecting** a parallel ordered [`Slot`] signature describing
//!    the kind of each replaced slot — preserves discrimination
//!    between (e.g.) `WHERE x = 42` (Integer literal) and
//!    `WHERE x = "42"` (String literal) when the structural form is
//!    the same.
//! 3. **Rendering** the canonical statement via its [`std::fmt::Display`]
//!    impl into a stable, deterministic byte sequence. The grammar's
//!    own round-trip discipline (`tests/grammar_proptest.rs`'s
//!    `roundtrip_parse_print_parse`) guarantees the rendered form is
//!    structurally faithful — the canonical bytestream is just the
//!    placeholder-substituted print.
//!
//! The bytestream is wrapped in `Arc<[u8]>` so cloning the key (LRU
//! insert, cross-tenant routing) is `O(1)` after the initial walk.
//!
//! Note: amendment-03 §TIER-2-a writes the key as
//! `(tenant_id, query_text, parameter-value-shape)`; this implementation
//! collapses `query_text` and `parameter-value-shape` into the single
//! canonical bytestream because they overlap by construction (canonical =
//! parser output of erased AST). Two queries with different `query_text`
//! but identical AST after canonicalization correctly share a cache entry
//! — this is the desired user-facing semantic, and is strictly stronger
//! than literal `query_text` discrimination (which would distinguish
//! whitespace-only variants).
//!
//! # Determinism
//!
//! Two `PlanCacheKey`s compare equal iff their `(tenant_id, canonical
//! bytestream, signature)` tuples are byte-equal. The bytestream is
//! generated by [`std::fmt::Display`] which is deterministic across
//! processes (no `std::hash::DefaultHasher` random seed). The
//! [`std::hash::Hash`] impl walks the same fields, so cache-internal
//! HashMap distribution is also process-stable.
//!
//! # Out-of-scope canonicalizations (v1.0)
//!
//! - **Variable name aliasing.** `MATCH (n) RETURN n` and
//!   `MATCH (m) RETURN m` produce DIFFERENT keys because the canonical
//!   bytestream preserves user-chosen variable names (the cached
//!   [`crate::planner::cost::CostedPlan`] would otherwise render with
//!   the wrong variable name on hit). Forward-link: v1.1 may
//!   canonicalize variable names + carry a re-mapping table on hit.
//! - **Map key reordering.** `{a: 1, b: 2}` and `{b: 2, a: 1}` produce
//!   DIFFERENT keys; the parser preserves source order and v1.0 keeps
//!   that conservative posture.
//! - **Property-list reordering inside patterns.** Same conservatism.
//!
//! # ADR provenance
//! - ADR-038 amendment-03 §TIER-2-a — cache-key contract (this module
//!   implements its `parameter-erased AST + parameter-type signature`
//!   half).

use std::sync::Arc;

use arcgraph_core::TenantId;

use crate::ast::{
    CallClause, Clause, CreateClause, CreateItem, DeleteClause, Expression, LengthRange, Literal,
    MapProjectionItem, MatchBody, MatchClause, MergeClause, MergePattern, NamedPath, NamedPathKind,
    NodePattern, OrderItem, PathPattern, ProjectionItem, ProjectionKind, PropertyMap, RankArg,
    RankByClause, Ranker, ReadQuery, RelPattern, RemoveClause, ReturnClause, SetClause, SetItem,
    SetMutation, Statement, UnwindClause, WithClause, WithFusionClause,
};

/// Parameter-erasure cache key.
///
/// Two `PlanCacheKey`s compare equal iff their tenant, canonical
/// bytestream, AND parameter-type signature are all byte-equal. The
/// canonical bytestream alone is insufficient because two queries
/// differing in literal KIND at the same syntactic position
/// (`WHERE x = 42` vs `WHERE x = "abc"`) can share a structural
/// shape; the signature breaks the tie.
#[derive(Debug, Clone)]
pub struct PlanCacheKey {
    /// Tenant identity per ADR-037 multi-tenancy P0. Cache entries
    /// from one tenant NEVER serve another tenant.
    pub tenant_id: TenantId,
    /// Canonical print of the statement with every literal value /
    /// parameter slot replaced with a kind-preserving placeholder.
    /// Wrapped in `Arc` so clone is `O(1)` (per-tenant LRU clones the
    /// key on insert).
    canonical: Arc<[u8]>,
    /// Ordered slot signature describing each replaced position.
    signature: Arc<[Slot]>,
}

impl PlanCacheKey {
    /// Derive the cache key for `(tenant_id, statement)`.
    ///
    /// The statement is cloned and walked in-place; the original AST
    /// is NOT mutated (callers retain the original for the lower /
    /// enumerate / cost passes on the cache-miss path).
    ///
    /// Budget: O(plan-AST-size). For v1.0 plan sizes (≤ 50 nodes,
    /// ≤ 10 predicates) this completes in microseconds — well inside
    /// the 5 ms M4-05 plan-build budget per ADR-036 §D-25.
    #[must_use]
    pub fn from_ast(tenant_id: TenantId, statement: &Statement) -> Self {
        let mut clone = statement.clone();
        let mut signature: Vec<Slot> = Vec::new();
        canonicalize_statement(&mut clone, &mut signature);
        let canonical = format!("{clone}").into_bytes();
        Self {
            tenant_id,
            canonical: Arc::from(canonical.into_boxed_slice()),
            signature: Arc::from(signature.into_boxed_slice()),
        }
    }

    /// Tenant identity for this key.
    #[must_use]
    pub fn tenant_id(&self) -> TenantId {
        self.tenant_id
    }

    /// Borrow the canonical bytestream. Useful for tests that need to
    /// assert the canonicalization output.
    #[must_use]
    pub fn canonical(&self) -> &[u8] {
        &self.canonical
    }

    /// Borrow the parameter-type signature in source order.
    #[must_use]
    pub fn signature(&self) -> &[Slot] {
        &self.signature
    }
}

impl PartialEq for PlanCacheKey {
    fn eq(&self, other: &Self) -> bool {
        self.tenant_id == other.tenant_id
            && self.canonical == other.canonical
            && self.signature == other.signature
    }
}

impl Eq for PlanCacheKey {}

impl std::hash::Hash for PlanCacheKey {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        self.tenant_id.hash(state);
        self.canonical.hash(state);
        self.signature.hash(state);
    }
}

/// One position in the parameter-type signature.
///
/// The walk emits a [`Slot`] for every replaced site in source order.
/// Two `PlanCacheKey`s with identical canonical bytestreams but
/// different `Slot` sequences are distinct entries — this preserves
/// type discrimination across cache shapes when literal kinds change
/// at the same syntactic position.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum Slot {
    /// An inline value literal slot. Carries the kind so a literal at
    /// position `i` of one query is distinct from a different-kind
    /// literal at position `i` of another query.
    Lit(LitKind),
    /// A parameter reference slot. Carries the parameter NAME so
    /// `$id` and `$ident` produce distinct keys (conservative; v1.1
    /// may canonicalize names if profiling justifies).
    Param(String),
}

/// Literal-value kind tracked in [`Slot::Lit`].
///
/// `Null` and the structural `List` / `Map` variants are NOT in this
/// enum — those participate in the canonical bytestream directly
/// (Null prints as `NULL`; List / Map render structurally with their
/// inner element slots replaced individually).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum LitKind {
    /// `Literal::Bool` slot.
    Bool,
    /// `Literal::Integer` slot.
    Integer,
    /// `Literal::Float` slot.
    Float,
    /// `Literal::String` slot.
    String,
    // W23-V11-T-01 / ADR-090 — temporal + decimal literal slots
    // participate in the plan-cache key. The slot kind is what the
    // canonicalizer compares; the constructor's inner value is
    // erased (the cache key is parameter-shape-only per ADR-038
    // amendment-06 §"plan-cache rationale").
    /// `Literal::Temporal(ZonedDateTime)` slot.
    Temporal,
    /// `Literal::LocalDateTime` slot.
    LocalDateTime,
    /// `Literal::Date` slot.
    Date,
    /// `Literal::Duration` slot.
    Duration,
    /// `Literal::Decimal` slot.
    Decimal,
}

// ---------------------------------------------------------------------
// Canonicalization walkers
// ---------------------------------------------------------------------

fn canonicalize_statement(stmt: &mut Statement, sig: &mut Vec<Slot>) {
    match stmt {
        Statement::Read(q) | Statement::Explain(q) | Statement::Profile(q) => {
            canonicalize_read_query(q, sig);
        }
        Statement::IndexDdl(_) => {}
        // ADR-185 (#649-A1, W28) — UNION / UNION ALL. Canonicalize the
        // literal payloads of every arm + the post-union tail
        // expressions so two unions differing only in literal values
        // hash to the SAME plan shape (parameter-shape-only key per
        // ADR-038 amendment-06). The arm count + per-boundary `all`
        // flags + tail structure are NOT erased: they ride in the
        // canonical bytestream via `UnionQuery`'s `Display` impl, so
        // `… UNION …` and `… UNION ALL …` hash to DISTINCT plan-cache
        // entries (they lower to different plans — concat vs
        // concat+distinct).
        Statement::Union(u) => {
            for arm in &mut u.arms {
                canonicalize_read_query(arm, sig);
            }
            for it in &mut u.tail.order_by {
                canonicalize_order_item(it, sig);
            }
            if let Some(e) = &mut u.tail.skip {
                canonicalize_expression(e, sig);
            }
            if let Some(e) = &mut u.tail.limit {
                canonicalize_expression(e, sig);
            }
        }
    }
}

fn canonicalize_read_query(q: &mut ReadQuery, sig: &mut Vec<Slot>) {
    for clause in &mut q.clauses {
        canonicalize_clause(clause, sig);
    }
}

fn canonicalize_clause(clause: &mut Clause, sig: &mut Vec<Slot>) {
    match clause {
        Clause::Match(m) | Clause::OptionalMatch(m) => canonicalize_match_clause(m, sig),
        Clause::Create(c) => canonicalize_create_clause(c, sig),
        Clause::Delete(d) => canonicalize_delete_clause(d, sig),
        Clause::Set(s) => canonicalize_set_clause(s, sig),
        Clause::Remove(r) => canonicalize_remove_clause(r, sig),
        Clause::Merge(m) => canonicalize_merge_clause(m, sig),
        Clause::With(w) => canonicalize_with_clause(w, sig),
        Clause::Unwind(u) => canonicalize_unwind_clause(u, sig),
        Clause::Call(c) => canonicalize_call_clause(c, sig),
        // ADR-197 (#802): the procedure NAME + YIELD column shape are
        // part of the plan identity (different procedures → different
        // plans), so reuse the name-preserving `Slot::Param` to carry
        // them; the arg expressions canonicalize as literals/params.
        Clause::CallProcedure(c) => {
            sig.push(Slot::Param(format!("proc:{}", c.name)));
            for (col, alias) in &c.yield_items {
                sig.push(Slot::Param(format!(
                    "yield:{col}:{}",
                    alias.as_deref().unwrap_or("")
                )));
            }
            for a in &mut c.args {
                canonicalize_expression(a, sig);
            }
            if let Some(w) = &mut c.where_clause {
                canonicalize_expression(w, sig);
            }
        }
        Clause::Show(c) => {
            let kind = match c.kind {
                crate::ast::ShowKind::Constraints => "constraints",
                crate::ast::ShowKind::Indexes => "indexes",
                crate::ast::ShowKind::Databases => "databases",
                crate::ast::ShowKind::VectorIndexes => "vector_indexes",
            };
            sig.push(Slot::Param(format!("show:{kind}")));
            // #830 — the YIELD column/alias set + the WHERE predicate are
            // part of the query shape; two SHOWs differing in either must
            // NOT share a plan-cache slot (mirrors `Clause::CallProcedure`).
            for (col, alias) in &c.yield_items {
                sig.push(Slot::Param(format!(
                    "yield:{col}:{}",
                    alias.as_deref().unwrap_or("")
                )));
            }
            if let Some(w) = &mut c.where_clause {
                canonicalize_expression(w, sig);
            }
        }
        Clause::RankBy(r) => canonicalize_rank_by_clause(r, sig),
        Clause::WithFusion(wf) => canonicalize_with_fusion_clause(wf, sig),
        Clause::Return(r) => canonicalize_return_clause(r, sig),
        Clause::TailOrderBy(items) => {
            for it in items {
                canonicalize_order_item(it, sig);
            }
        }
        Clause::TailSkip(e) | Clause::TailLimit(e) => canonicalize_expression(e, sig),
    }
}

// ADR-147 W26-θ Phase 1 + ADR-148 W26-θ Phase 2: CREATE clauses do not
// currently contribute to the plan-cache signature beyond their literal
// property values (labels + variable names are name-preserving like
// MATCH clauses). The plan-cache key MUST canonicalize the property-bag
// literals via the standard `canonicalize_expression` walk so writes
// with different literal payloads hash the same plan shape.
//
// Phase 2 extends the walk to cover the source + rel + target sub-shapes
// of `CreateItem::Path` — the rel-label name is name-preserving (same
// rationale as the rel-pattern type in MATCH; the plan-cache key relies
// on structural sub-substitution, not name-identity).
// ADR-149 W26-θ Phase 3: DELETE clauses do not contribute to the
// plan-cache `Slot` signature — DELETE arguments are bare identifier
// references (no literals or parameters at Phase 3 per ADR-149 §D-1),
// and identifier names ride in the canonical bytestream via the
// `Display` round-trip (parallel to MATCH-bound variable name
// handling). The `detach: bool` flag is structurally significant but
// is preserved in the canonical bytestream via `DeleteClause`'s
// `Display` impl (the `DETACH DELETE ...` prefix versus the plain
// `DELETE ...` prefix). Two queries differing only in DETACH thus
// hash to distinct plan-cache entries via the canonical bytestream
// alone — no per-clause Slot contribution needed.
fn canonicalize_delete_clause(_d: &mut DeleteClause, _sig: &mut Vec<Slot>) {
    // Intentionally empty — see rustdoc above.
}

// ADR-150 W26-θ Phase 4: SET clauses canonicalize the property-value
// sub-expressions inside the four set_item shapes. Item-shape
// distinction (assign / merge / replace / label-add) is already
// preserved in the canonical bytestream via the `SetItem` / `SetMutation`
// `Display` impls; this walker only adds Slot entries for the literal
// payloads so two queries that differ only in literal values hash the
// same plan-cache entry while two queries with different literal types
// hash distinct entries (parallel to the CREATE canonicalization
// rationale).
fn canonicalize_set_clause(s: &mut SetClause, sig: &mut Vec<Slot>) {
    for item in &mut s.items {
        canonicalize_set_item(item, sig);
    }
}

fn canonicalize_set_item(item: &mut SetItem, sig: &mut Vec<Slot>) {
    match &mut item.mutation {
        SetMutation::PropertyAssign { value, .. } => canonicalize_expression(value, sig),
        SetMutation::PropertyReplace(map) | SetMutation::PropertyMerge(map) => {
            for (_, value) in map.entries.iter_mut() {
                canonicalize_expression(value, sig);
            }
        }
        SetMutation::LabelAdd(_) => {
            // Label names are name-preserving (same rationale as
            // CREATE-node labels); the canonical bytestream carries
            // them via `SetItem`'s `Display` impl. No Slot
            // contribution.
        }
    }
}

// ADR-150 W26-θ Phase 4: REMOVE clauses contribute NO Slot entries
// — both item shapes (property-name + label-list) are
// name-preserving and ride in the canonical bytestream via `Display`
// (parallel to the DELETE rationale above).
fn canonicalize_remove_clause(_r: &mut RemoveClause, _sig: &mut Vec<Slot>) {
    // Intentionally empty — see rustdoc above.
}

// ADR-151 W26-θ Phase 5: MERGE clauses canonicalize the property-bag
// literal payloads inside the merge pattern AND inside the on_create /
// on_match action items (parallel to the Phase 1 + 2 CREATE
// canonicalization + the Phase 4 SET canonicalization). Pattern shape
// distinction (Node vs Path) + branch distinction (ON CREATE vs ON
// MATCH) is preserved in the canonical bytestream via the
// `MergeClause` / `MergePattern` `Display` impls; this walker only
// adds Slot entries for literal payloads so two MERGE queries that
// differ only in literal values hash the same plan-cache entry, and
// two queries with different literal types hash distinct entries.
fn canonicalize_merge_clause(m: &mut MergeClause, sig: &mut Vec<Slot>) {
    // Pattern property-bag literals.
    match &mut m.pattern {
        MergePattern::Node(spec) => {
            if let Some(map) = spec.properties.as_mut() {
                for (_k, v) in &mut map.entries {
                    canonicalize_expression(v, sig);
                }
            }
        }
        MergePattern::Path(path) => {
            if let Some(map) = path.source.properties.as_mut() {
                for (_k, v) in &mut map.entries {
                    canonicalize_expression(v, sig);
                }
            }
            if let Some(map) = path.rel.properties.as_mut() {
                for (_k, v) in &mut map.entries {
                    canonicalize_expression(v, sig);
                }
            }
            if let Some(map) = path.target.properties.as_mut() {
                for (_k, v) in &mut map.entries {
                    canonicalize_expression(v, sig);
                }
            }
        }
    }
    // Action item literals (reuse Phase 4 canonicalize_set_item).
    for item in m.on_create.iter_mut().chain(m.on_match.iter_mut()) {
        canonicalize_set_item(item, sig);
    }
}

fn canonicalize_create_clause(c: &mut CreateClause, sig: &mut Vec<Slot>) {
    for item in &mut c.items {
        match item {
            CreateItem::Node(spec) => {
                if let Some(map) = spec.properties.as_mut() {
                    for (_k, v) in &mut map.entries {
                        canonicalize_expression(v, sig);
                    }
                }
            }
            CreateItem::Path(path) => {
                if let Some(map) = path.source.properties.as_mut() {
                    for (_k, v) in &mut map.entries {
                        canonicalize_expression(v, sig);
                    }
                }
                if let Some(map) = path.rel.properties.as_mut() {
                    for (_k, v) in &mut map.entries {
                        canonicalize_expression(v, sig);
                    }
                }
                if let Some(map) = path.target.properties.as_mut() {
                    for (_k, v) in &mut map.entries {
                        canonicalize_expression(v, sig);
                    }
                }
            }
        }
    }
}

fn canonicalize_match_clause(m: &mut MatchClause, sig: &mut Vec<Slot>) {
    canonicalize_match_body(&mut m.body, sig);
    if let Some(w) = m.where_clause.as_mut() {
        canonicalize_expression(w, sig);
    }
}

fn canonicalize_match_body(body: &mut MatchBody, sig: &mut Vec<Slot>) {
    match body {
        MatchBody::Patterns(patterns) => {
            for p in patterns {
                canonicalize_path_pattern(p, sig);
            }
        }
        MatchBody::NamedPath(np) => canonicalize_named_path(np, sig),
    }
}

fn canonicalize_named_path(np: &mut NamedPath, sig: &mut Vec<Slot>) {
    match &mut np.kind {
        NamedPathKind::ShortestPath(p)
        | NamedPathKind::AllShortestPath(p)
        | NamedPathKind::Plain(p) => {
            canonicalize_path_pattern(p, sig);
        }
    }
}

fn canonicalize_path_pattern(p: &mut PathPattern, sig: &mut Vec<Slot>) {
    canonicalize_node_pattern(&mut p.head, sig);
    for (rel, node) in &mut p.tail {
        canonicalize_rel_pattern(rel, sig);
        canonicalize_node_pattern(node, sig);
    }
}

fn canonicalize_node_pattern(n: &mut NodePattern, sig: &mut Vec<Slot>) {
    if let Some(props) = n.properties.as_mut() {
        canonicalize_property_map(props, sig);
    }
}

fn canonicalize_rel_pattern(r: &mut RelPattern, sig: &mut Vec<Slot>) {
    if let Some(LengthRange::Cypher { .. } | LengthRange::Quantified { .. }) = r.length {
        // Length ranges carry numeric `min/max` u32 values that ARE
        // shape-affecting (a `*1..3` range plans differently from a
        // `*5..10` range — different traversal depth). Keep the
        // numeric values in the canonical form.
    }
    if let Some(props) = r.properties.as_mut() {
        canonicalize_property_map(props, sig);
    }
}

fn canonicalize_property_map(props: &mut PropertyMap, sig: &mut Vec<Slot>) {
    for (_key, expr) in &mut props.entries {
        canonicalize_expression(expr, sig);
    }
}

fn canonicalize_with_clause(w: &mut WithClause, sig: &mut Vec<Slot>) {
    for item in &mut w.items {
        canonicalize_projection_item(item, sig);
    }
    if let Some(e) = w.where_clause.as_mut() {
        canonicalize_expression(e, sig);
    }
}

fn canonicalize_unwind_clause(u: &mut UnwindClause, sig: &mut Vec<Slot>) {
    canonicalize_expression(&mut u.expr, sig);
}

/// ADR-192 (#623): canonicalize a `CALL { <subquery> }` body so two
/// subqueries differing only in literal property values share a
/// plan-cache slot — the same name-preserving / literal-slotting
/// treatment a top-level read query gets. Recurses into the body's
/// clauses (Read) or each arm + the post-union tail (Union).
fn canonicalize_call_clause(c: &mut CallClause, sig: &mut Vec<Slot>) {
    match c.body.as_mut() {
        Statement::Read(q) => canonicalize_read_query(q, sig),
        Statement::Union(u) => {
            for arm in &mut u.arms {
                canonicalize_read_query(arm, sig);
            }
            for it in &mut u.tail.order_by {
                canonicalize_order_item(it, sig);
            }
            if let Some(e) = &mut u.tail.skip {
                canonicalize_expression(e, sig);
            }
            if let Some(e) = &mut u.tail.limit {
                canonicalize_expression(e, sig);
            }
        }
        // Grammar admits only Read/Union inside CALL{}.
        _ => {}
    }
}

fn canonicalize_rank_by_clause(r: &mut RankByClause, sig: &mut Vec<Slot>) {
    match &mut r.ranker {
        Ranker::Hybrid(args) => {
            for a in args {
                match a {
                    RankArg::Vector { query, .. } | RankArg::Text { query, .. } => {
                        canonicalize_expression(query, sig);
                    }
                }
            }
        }
    }
}

fn canonicalize_with_fusion_clause(_wf: &mut WithFusionClause, _sig: &mut Vec<Slot>) {}

fn canonicalize_return_clause(r: &mut ReturnClause, sig: &mut Vec<Slot>) {
    for item in &mut r.items {
        canonicalize_projection_item(item, sig);
    }
    for o in &mut r.order_by {
        canonicalize_order_item(o, sig);
    }
    if let Some(e) = r.skip.as_mut() {
        canonicalize_expression(e, sig);
    }
    if let Some(e) = r.limit.as_mut() {
        canonicalize_expression(e, sig);
    }
}

fn canonicalize_projection_item(p: &mut ProjectionItem, sig: &mut Vec<Slot>) {
    if let ProjectionKind::Expr(e) = &mut p.kind {
        canonicalize_expression(e, sig);
    }
}

fn canonicalize_order_item(o: &mut OrderItem, sig: &mut Vec<Slot>) {
    canonicalize_expression(&mut o.expr, sig);
}

fn canonicalize_expression(e: &mut Expression, sig: &mut Vec<Slot>) {
    match e {
        Expression::Literal(l) => canonicalize_literal(l, sig),
        Expression::Parameter(name) => {
            sig.push(Slot::Param(name.clone()));
            *name = String::from("__p");
        }
        Expression::Identifier(_) => { /* identifier names are shape-affecting; preserve */ }
        Expression::PropertyAccess { base, path: _ } => {
            // path is `Vec<String>` of property names (shape); preserve.
            canonicalize_expression(base, sig);
        }
        // #1290 — left-nested operator SPINE walked iteratively (the
        // spine can be `MAX_FLAT_CHAIN_DEPTH` deep and may interleave
        // BinaryOp / UnaryOp / In / IsNull levels; recursing per level
        // overflowed the native stack). The `sig` slot order MUST match
        // the recursion this replaces (the ordered signature is half
        // the cache key): base subtree first, then each level's rhs
        // innermost→outermost — exactly the recursive in-order. The
        // borrowed `&mut` rhs nodes collected on the way down are
        // disjoint subtrees, so holding them across the descent is
        // borrow-safe. `In` / `IsNull` keep no dedicated arms below —
        // this loop owns all four variants.
        Expression::BinaryOp { .. }
        | Expression::UnaryOp { .. }
        | Expression::In { .. }
        | Expression::IsNull { .. } => {
            let mut rhs_stack: Vec<&mut Expression> = Vec::new();
            let mut cur: &mut Expression = e;
            loop {
                match cur {
                    Expression::BinaryOp { op: _, lhs, rhs } => {
                        rhs_stack.push(rhs);
                        cur = lhs;
                    }
                    Expression::In { lhs, rhs } => {
                        rhs_stack.push(rhs);
                        cur = lhs;
                    }
                    Expression::UnaryOp { op: _, operand } => cur = operand,
                    Expression::IsNull { lhs, negated: _ } => cur = lhs,
                    other => {
                        canonicalize_expression(other, sig);
                        break;
                    }
                }
            }
            while let Some(rhs) = rhs_stack.pop() {
                canonicalize_expression(rhs, sig);
            }
        }
        Expression::FunctionCall {
            name: _,
            args,
            // `distinct` / `star` are shape-affecting (`count(*)` ≠
            // `count(x)` ≠ `count(DISTINCT x)` are DISTINCT plans). They
            // ride the cloned AST untouched and are rendered into the
            // canonical bytestream by `Display`, so the key discriminates
            // them — no literal/param erasure applies to a bare flag.
            distinct: _,
            star: _,
        } => {
            for a in args {
                canonicalize_expression(a, sig);
            }
        }
        Expression::Near {
            lhs,
            target,
            vector_index: _,
        } => {
            canonicalize_expression(lhs, sig);
            canonicalize_expression(target, sig);
        }
        Expression::TextMatch { lhs, query } => {
            canonicalize_expression(lhs, sig);
            canonicalize_expression(query, sig);
        }
        Expression::InCommunity { node, community } => {
            canonicalize_expression(node, sig);
            canonicalize_expression(community, sig);
        }
        // ADR-188 — the list-predicate quantifier keyword
        // (`all`/`any`/`none`/`single`) + the `reduce` shape + the
        // iteration-variable names ride in the canonical bytestream via
        // `Expression`'s `Display` impl (parallel to MATCH-bound
        // variable names). We recurse into every sub-expression so
        // inner literals are parameterized (e.g.
        // `all(x IN l WHERE x > 1)` and `all(x IN l WHERE x > 2)` share
        // a plan key with the literal slot erased).
        Expression::ListPredicate {
            quantifier: _,
            var: _,
            list,
            predicate,
        } => {
            canonicalize_expression(list, sig);
            canonicalize_expression(predicate, sig);
        }
        Expression::Reduce {
            acc_var: _,
            init,
            var: _,
            list,
            expr,
        } => {
            canonicalize_expression(init, sig);
            canonicalize_expression(list, sig);
            canonicalize_expression(expr, sig);
        }
        // ADR-188 (#620 list-half) — the list-comprehension shape (the
        // `[x IN … (WHERE …)? (| …)?]` skeleton + the iteration-variable
        // name + which of WHERE / `|` are present) rides in the
        // canonical bytestream via `Expression`'s `Display` impl
        // (parallel to the `ListPredicate` / `Reduce` treatment above).
        // We recurse into every sub-expression (list + optional
        // predicate + optional projection) so inner literals are
        // parameterized — e.g. `[x IN l WHERE x > 1 | x]` and
        // `[x IN l WHERE x > 2 | x]` share a plan key with the literal
        // slot erased, while a structurally-different comprehension
        // (different presence of WHERE / `|`) keys distinctly because
        // its Display bytestream differs.
        Expression::ListComprehension {
            var: _,
            list,
            predicate,
            projection,
        } => {
            canonicalize_expression(list, sig);
            if let Some(p) = predicate {
                canonicalize_expression(p, sig);
            }
            if let Some(e) = projection {
                canonicalize_expression(e, sig);
            }
        }
        // ADR-191 D-6 (#620 map-half) — the map-projection shape (the base
        // variable name + each `.key` / `.*` selector + each `alias:`) is
        // shape-affecting and rides in the canonical bytestream via
        // `Expression`'s `Display` impl (parallel to the comprehension
        // treatment above). We recurse ONLY into the literal-entry VALUE
        // expressions so their inner literals are parameterized — e.g.
        // `n{x: 1}` and `n{x: 2}` share a plan key with the literal slot
        // erased, while a structurally-different projection (different
        // selectors / aliases) keys distinctly because its Display
        // bytestream differs.
        Expression::MapProjection { base: _, items } => {
            for item in items.iter_mut() {
                if let MapProjectionItem::Literal { alias: _, value } = item {
                    canonicalize_expression(value, sig);
                }
            }
        }
        // openCypher v9 §3.4 — postfix accessors. The `[..]` / `[i]`
        // skeleton rides in the canonical bytestream via `Display`;
        // recurse into the base + index / bounds so inner literals are
        // parameterized (e.g. `list[0]` and `list[1]` share a plan key
        // with the index-literal slot erased).
        Expression::Subscript { base, index } => {
            canonicalize_expression(base, sig);
            canonicalize_expression(index, sig);
        }
        Expression::Slice { base, start, end } => {
            canonicalize_expression(base, sig);
            if let Some(s) = start {
                canonicalize_expression(s, sig);
            }
            if let Some(e) = end {
                canonicalize_expression(e, sig);
            }
        }
        // openCypher v9 §3.6 (#621) — the CASE STRUCTURE (simple vs searched
        // = presence of the leading test; the WHEN/THEN/ELSE skeleton; the
        // arm count) rides in the canonical bytestream via `Expression`'s
        // `Display` impl (parallel to the comprehension / accessor treatment
        // above), so two structurally-different CASE expressions key
        // distinctly. We recurse into EVERY sub-expression (test + each WHEN
        // + each THEN + ELSE) so their inner literals are parameterized —
        // e.g. `CASE x WHEN 1 THEN 'a' END` and `CASE x WHEN 2 THEN 'a' END`
        // share a plan key with the literal slots erased, while
        // `CASE x WHEN 1 THEN 'a' ELSE 'b' END` (an extra ELSE arm) keys
        // distinctly because its Display bytestream differs.
        Expression::Case {
            test,
            branches,
            default,
        } => {
            if let Some(t) = test {
                canonicalize_expression(t, sig);
            }
            for (when, then) in branches.iter_mut() {
                canonicalize_expression(when, sig);
                canonicalize_expression(then, sig);
            }
            if let Some(d) = default {
                canonicalize_expression(d, sig);
            }
        }
    }
}

fn canonicalize_literal(l: &mut Literal, sig: &mut Vec<Slot>) {
    match l {
        Literal::Null => { /* shape-affecting; preserve */ }
        Literal::Bool(v) => {
            sig.push(Slot::Lit(LitKind::Bool));
            *v = false;
        }
        Literal::Integer(v) => {
            sig.push(Slot::Lit(LitKind::Integer));
            *v = 0;
        }
        Literal::Float(v) => {
            sig.push(Slot::Lit(LitKind::Float));
            *v = 0.0;
        }
        Literal::String(s) => {
            sig.push(Slot::Lit(LitKind::String));
            s.clear();
        }
        Literal::List(xs) => {
            for x in xs {
                canonicalize_expression(x, sig);
            }
        }
        Literal::Map(es) => {
            for (_k, v) in es {
                canonicalize_expression(v, sig);
            }
        }
        // W23-V11-T-01 / ADR-090 — temporal + decimal canonicalizer.
        // Push the slot kind; do NOT mutate the inner value (these
        // are Copy newtypes; the canonical form keeps the slot kind
        // as the cache-key discriminator).
        Literal::Temporal(_) => sig.push(Slot::Lit(LitKind::Temporal)),
        Literal::LocalDateTime(_) => sig.push(Slot::Lit(LitKind::LocalDateTime)),
        Literal::Date(_) => sig.push(Slot::Lit(LitKind::Date)),
        Literal::Duration(_) => sig.push(Slot::Lit(LitKind::Duration)),
        Literal::Decimal(_) => sig.push(Slot::Lit(LitKind::Decimal)),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parse;

    fn key_for(query: &str, tenant: TenantId) -> PlanCacheKey {
        let stmt = parse(query).expect("parse");
        PlanCacheKey::from_ast(tenant, &stmt)
    }

    #[test]
    fn equal_queries_produce_equal_keys() {
        let a = key_for("MATCH (n:Person) RETURN n", TenantId::DEFAULT);
        let b = key_for("MATCH (n:Person) RETURN n", TenantId::DEFAULT);
        assert_eq!(a, b);
    }

    #[test]
    fn different_tenants_produce_different_keys() {
        let a = key_for("MATCH (n:Person) RETURN n", TenantId::new(1));
        let b = key_for("MATCH (n:Person) RETURN n", TenantId::new(2));
        assert_ne!(a, b);
    }

    #[test]
    fn integer_literal_values_canonicalize_equal() {
        // The canonical pin from spawn-prompt §A — two queries
        // differing only in inline integer literal values must share
        // a cache entry.
        let a = key_for("MATCH (n {id: 42}) RETURN n", TenantId::DEFAULT);
        let b = key_for("MATCH (n {id: 43}) RETURN n", TenantId::DEFAULT);
        assert_eq!(a, b);
    }

    #[test]
    fn parameter_values_canonicalize_equal_when_names_match() {
        // Same parameter NAME → same signature → equal keys (parameter
        // values aren't in the AST, so this is structural).
        let a = key_for("MATCH (n) WHERE n.id = $id RETURN n", TenantId::DEFAULT);
        let b = key_for("MATCH (n) WHERE n.id = $id RETURN n", TenantId::DEFAULT);
        assert_eq!(a, b);
    }

    #[test]
    fn parameter_names_distinguish_keys() {
        // Different parameter NAMES → different signatures → different
        // keys (conservative posture per module rustdoc §"Out-of-scope
        // canonicalizations").
        let a = key_for("MATCH (n) WHERE n.id = $id RETURN n", TenantId::DEFAULT);
        let b = key_for("MATCH (n) WHERE n.id = $other RETURN n", TenantId::DEFAULT);
        assert_ne!(a, b);
    }

    #[test]
    fn integer_vs_string_literal_kinds_distinguish_keys() {
        // Same syntactic position but different literal KINDS must
        // produce different keys — `n.id = 42` (Integer) plans
        // differently from `n.id = "42"` (String).
        let a = key_for("MATCH (n) WHERE n.id = 42 RETURN n", TenantId::DEFAULT);
        let b = key_for(r#"MATCH (n) WHERE n.id = "42" RETURN n"#, TenantId::DEFAULT);
        assert_ne!(a, b);
    }

    #[test]
    fn float_vs_integer_literal_kinds_distinguish_keys() {
        // Float vs Integer at the same syntactic position must produce
        // DIFFERENT cache keys — the cost-walker treats `n.x = 42`
        // (Integer) and `n.x = 42.0` (Float) as distinct predicate
        // shapes (numeric-vs-numeric type promotion + index probe shape
        // can diverge). Closes M4-53 review Sin #1 (literal-kind
        // preservation cross-product gap).
        let key_int = key_for("MATCH (n) WHERE n.x = 42 RETURN n", TenantId::DEFAULT);
        let key_float = key_for("MATCH (n) WHERE n.x = 42.0 RETURN n", TenantId::DEFAULT);
        assert_ne!(
            key_int, key_float,
            "Integer 42 and Float 42.0 at the same syntactic position must produce \
             distinct cache keys (literal-kind preservation)",
        );
    }

    #[test]
    fn bool_vs_integer_literal_kinds_distinguish_keys() {
        // Bool vs Integer at the same syntactic position must produce
        // DIFFERENT cache keys — `n.x = TRUE` (Bool) and `n.x = 1`
        // (Integer) plan differently even though boolean coercion would
        // give matching runtime semantics on some backends. Closes
        // M4-53 review Sin #2 (literal-kind preservation cross-product
        // gap).
        let key_bool = key_for("MATCH (n) WHERE n.x = TRUE RETURN n", TenantId::DEFAULT);
        let key_int = key_for("MATCH (n) WHERE n.x = 1 RETURN n", TenantId::DEFAULT);
        assert_ne!(
            key_bool, key_int,
            "Bool TRUE and Integer 1 at the same syntactic position must produce \
             distinct cache keys (literal-kind preservation)",
        );
    }

    #[test]
    fn variable_names_are_not_canonicalized() {
        // v1.0 conservative: variable name participates in the
        // canonical bytestream so the cached PlanTree's rendered
        // variable name matches the user's. Pinned by module rustdoc.
        let a = key_for("MATCH (n:Person) RETURN n", TenantId::DEFAULT);
        let b = key_for("MATCH (m:Person) RETURN m", TenantId::DEFAULT);
        assert_ne!(a, b);
    }

    #[test]
    fn signature_records_each_slot_in_source_order() {
        // Mixed parameter + literal slots; signature must reflect the
        // source-order traversal so a cache-key consumer can reason
        // about (e.g.) parameter binding count.
        let key = key_for(
            "MATCH (n:Person {id: 42}) WHERE n.age > $threshold RETURN n",
            TenantId::DEFAULT,
        );
        // 1 inline integer literal + 1 parameter. (Property-key names
        // are NOT slots; they're shape.)
        assert_eq!(
            key.signature(),
            &[
                Slot::Lit(LitKind::Integer),
                Slot::Param("threshold".to_string())
            ]
        );
    }

    // ---------- ADR-188 list-predicate / reduce cache-key ripple ----------
    // N-1 (R1 PR #723): the new `ListPredicate`/`Reduce` AST variants ride
    // the canonical bytestream via their `Display` impls (the quantifier
    // keyword + scoped-var name are shape, the inner literals are erased to
    // `Slot` placeholders). These tests pin the two properties a cache-key
    // ripple must satisfy: (a) structurally-different forms produce DISTINCT
    // keys (no collision), and (b) literal-only diffs COLLAPSE (correctly
    // parameterized). Same discipline as the `*_literal_kinds_distinguish`
    // + `integer_literal_values_canonicalize_equal` tests above.

    #[test]
    fn list_predicate_quantifiers_produce_distinct_keys() {
        // all / any / none / single over the SAME list + predicate must
        // produce DISTINCT cache keys — the quantifier keyword rides the
        // canonical bytestream (via `Expression::ListPredicate`'s Display),
        // so they cannot collide (they plan/evaluate differently).
        let all = key_for(
            "MATCH (n:X) WHERE all(x IN [1, 2, 3] WHERE x > 1) RETURN n",
            TenantId::DEFAULT,
        );
        let any = key_for(
            "MATCH (n:X) WHERE any(x IN [1, 2, 3] WHERE x > 1) RETURN n",
            TenantId::DEFAULT,
        );
        let none = key_for(
            "MATCH (n:X) WHERE none(x IN [1, 2, 3] WHERE x > 1) RETURN n",
            TenantId::DEFAULT,
        );
        let single = key_for(
            "MATCH (n:X) WHERE single(x IN [1, 2, 3] WHERE x > 1) RETURN n",
            TenantId::DEFAULT,
        );
        assert_ne!(all, any, "all(...) and any(...) must produce distinct keys");
        assert_ne!(
            any, none,
            "any(...) and none(...) must produce distinct keys"
        );
        assert_ne!(
            none, single,
            "none(...) and single(...) must produce distinct keys"
        );
        assert_ne!(
            all, single,
            "all(...) and single(...) must produce distinct keys"
        );
    }

    #[test]
    fn list_predicate_literal_only_diff_collapses() {
        // Two `all(...)` predicates differing ONLY in an inline integer
        // literal value (`x > 1` vs `x > 2`) must SHARE a cache entry —
        // the literal erases to a `Slot::Lit(Integer)` placeholder, so the
        // canonical shape is identical (correct parameterization).
        let a = key_for(
            "MATCH (n:X) WHERE all(x IN [1, 2, 3] WHERE x > 1) RETURN n",
            TenantId::DEFAULT,
        );
        let b = key_for(
            "MATCH (n:X) WHERE all(x IN [1, 2, 3] WHERE x > 2) RETURN n",
            TenantId::DEFAULT,
        );
        assert_eq!(
            a, b,
            "all(...) predicates differing only in an inline literal value must collapse"
        );
    }

    #[test]
    fn reduce_literal_only_diff_collapses() {
        // Two `reduce(...)` folds differing ONLY in the inline `init`
        // literal value (`s = 0` vs `s = 10`) must SHARE a cache entry —
        // the init literal erases to a `Slot::Lit(Integer)` placeholder.
        let a = key_for(
            "MATCH (n:X) RETURN reduce(s = 0, x IN [1, 2, 3] | s + x) AS t",
            TenantId::DEFAULT,
        );
        let b = key_for(
            "MATCH (n:X) RETURN reduce(s = 10, x IN [1, 2, 3] | s + x) AS t",
            TenantId::DEFAULT,
        );
        assert_eq!(
            a, b,
            "reduce(...) folds differing only in the init literal value must collapse"
        );
    }

    #[test]
    fn reduce_and_list_predicate_produce_distinct_keys() {
        // `reduce(...)` and `all(...)` are structurally distinct forms
        // (Reduce vs ListPredicate) and must NOT collide.
        let reduce = key_for(
            "MATCH (n:X) RETURN reduce(s = 0, x IN [1, 2, 3] | s + x) AS t",
            TenantId::DEFAULT,
        );
        let all = key_for(
            "MATCH (n:X) RETURN all(x IN [1, 2, 3] WHERE x > 0) AS t",
            TenantId::DEFAULT,
        );
        assert_ne!(
            reduce, all,
            "reduce(...) and all(...) must produce distinct keys"
        );
    }

    // ---------- ADR-188 (#620 list-half) list-comprehension cache-key ----------
    // Same #723 R1 ripple discipline: the `ListComprehension` AST variant
    // rides the canonical bytestream via its `Display` impl (the
    // iteration-variable name + which of WHERE / `|` are present are
    // shape; inner literals erase to `Slot` placeholders). These pin the
    // two properties the ripple must satisfy: (a) structurally-different
    // comprehensions produce DISTINCT keys, and (b) literal-only diffs
    // COLLAPSE.

    #[test]
    fn list_comprehension_shape_variants_produce_distinct_keys() {
        // The four §3.5 combinations over the SAME list differ in their
        // canonical bytestream (presence of WHERE / `|`), so they must
        // produce DISTINCT keys (they evaluate differently).
        let filter_map = key_for(
            "MATCH (n:X) RETURN [x IN [1, 2, 3] WHERE x > 1 | x * 10] AS ys",
            TenantId::DEFAULT,
        );
        let map_only = key_for(
            "MATCH (n:X) RETURN [x IN [1, 2, 3] | x * 10] AS ys",
            TenantId::DEFAULT,
        );
        let filter_only = key_for(
            "MATCH (n:X) RETURN [x IN [1, 2, 3] WHERE x > 1] AS ys",
            TenantId::DEFAULT,
        );
        let identity = key_for(
            "MATCH (n:X) RETURN [x IN [1, 2, 3]] AS ys",
            TenantId::DEFAULT,
        );
        assert_ne!(filter_map, map_only, "filter+map vs map-only must differ");
        assert_ne!(map_only, filter_only, "map-only vs filter-only must differ");
        assert_ne!(filter_only, identity, "filter-only vs identity must differ");
        assert_ne!(filter_map, identity, "filter+map vs identity must differ");
    }

    #[test]
    fn list_comprehension_literal_only_diff_collapses() {
        // Two comprehensions differing ONLY in inline integer literal
        // values (`x > 1 | x * 10` vs `x > 2 | x * 20`) must SHARE a cache
        // entry — the literals erase to `Slot::Lit(Integer)` placeholders,
        // so the canonical shape is identical.
        let a = key_for(
            "MATCH (n:X) RETURN [x IN [1, 2, 3] WHERE x > 1 | x * 10] AS ys",
            TenantId::DEFAULT,
        );
        let b = key_for(
            "MATCH (n:X) RETURN [x IN [1, 2, 3] WHERE x > 2 | x * 20] AS ys",
            TenantId::DEFAULT,
        );
        assert_eq!(
            a, b,
            "comprehensions differing only in inline literal values must collapse"
        );
    }

    #[test]
    fn list_comprehension_and_list_literal_produce_distinct_keys() {
        // A list COMPREHENSION `[x IN [1,2,3] | x]` and a plain list
        // LITERAL `[1, 2, 3]` are structurally distinct (ListComprehension
        // vs Literal::List) and must NOT collide — the disambiguation
        // carries through to the cache key.
        let comp = key_for(
            "MATCH (n:X) RETURN [x IN [1, 2, 3] | x] AS ys",
            TenantId::DEFAULT,
        );
        let literal = key_for("MATCH (n:X) RETURN [1, 2, 3] AS ys", TenantId::DEFAULT);
        assert_ne!(
            comp, literal,
            "list comprehension and list literal must produce distinct keys"
        );
    }

    #[test]
    fn list_comprehension_and_list_predicate_produce_distinct_keys() {
        // A list comprehension and a list predicate over the same list are
        // structurally distinct forms and must NOT collide.
        let comp = key_for(
            "MATCH (n:X) RETURN [x IN [1, 2, 3] WHERE x > 0 | x] AS ys",
            TenantId::DEFAULT,
        );
        let pred = key_for(
            "MATCH (n:X) RETURN all(x IN [1, 2, 3] WHERE x > 0) AS ys",
            TenantId::DEFAULT,
        );
        assert_ne!(
            comp, pred,
            "list comprehension and list predicate must produce distinct keys"
        );
    }
}
