//! ID newtypes used across the ArcGraph workspace.
//!
//! All IDs are `Copy` u64/u32 wrappers that derive the full comparison
//! and hashing surface. Serde is derived so higher-level metadata can
//! round-trip these through configuration and diagnostics formats.
//! The binary record format (see `crate::record`) does **not** use
//! serde; it serializes these as plain little-endian integers.

use serde::{Deserialize, Serialize};

macro_rules! define_u64_id {
    ($(#[$meta:meta])* $name:ident) => {
        $(#[$meta])*
        #[derive(
            Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize,
        )]
        #[repr(transparent)]
        #[serde(transparent)]
        pub struct $name(pub u64);

        impl $name {
            /// The zero value. Safe to use as a "null" sentinel only in
            /// contexts where the caller proves it is unused.
            pub const ZERO: Self = Self(0);

            /// The maximum value. Used as the "alive" sentinel for
            /// `expired_lsn` on MVCC-live records.
            pub const MAX: Self = Self(u64::MAX);

            /// Construct from a raw u64.
            #[inline]
            #[must_use]
            pub const fn new(raw: u64) -> Self {
                Self(raw)
            }

            /// The raw u64 representation.
            #[inline]
            #[must_use]
            pub const fn raw(self) -> u64 {
                self.0
            }
        }

        impl From<u64> for $name {
            #[inline]
            fn from(v: u64) -> Self {
                Self(v)
            }
        }

        impl From<$name> for u64 {
            #[inline]
            fn from(v: $name) -> Self {
                v.0
            }
        }
    };
}

macro_rules! define_u32_id {
    ($(#[$meta:meta])* $name:ident) => {
        $(#[$meta])*
        #[derive(
            Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize,
        )]
        #[repr(transparent)]
        #[serde(transparent)]
        pub struct $name(pub u32);

        impl $name {
            pub const ZERO: Self = Self(0);
            pub const MAX: Self = Self(u32::MAX);

            #[inline]
            #[must_use]
            pub const fn new(raw: u32) -> Self {
                Self(raw)
            }

            #[inline]
            #[must_use]
            pub const fn raw(self) -> u32 {
                self.0
            }
        }

        impl From<u32> for $name {
            #[inline]
            fn from(v: u32) -> Self {
                Self(v)
            }
        }

        impl From<$name> for u32 {
            #[inline]
            fn from(v: $name) -> Self {
                v.0
            }
        }
    };
}

define_u64_id!(
    /// 8-byte page identifier in the on-disk page store.
    PageId
);
define_u64_id!(
    /// 8-byte node identifier in the graph.
    NodeId
);
define_u64_id!(
    /// 8-byte relationship identifier in the graph.
    RelId
);
define_u64_id!(
    /// MVCC logical sequence number. Monotonically increasing per commit.
    /// `Lsn::ZERO` is the "never seen" floor; `Lsn::MAX` is the "alive"
    /// sentinel for `expired_lsn`.
    Lsn
);

define_u32_id!(
    /// Interned node-label identifier.
    LabelId
);
define_u32_id!(
    /// Interned relationship-type identifier.
    TypeId
);
define_u32_id!(
    /// Interned string identifier (property keys, string property values
    /// that fit in the intern table).
    StringId
);
define_u32_id!(
    /// Interned property-key identifier. Distinct from [`StringId`] —
    /// `PropertyId` is a label/type-style interned ID for property
    /// keys in the schema catalog (resolved at bind time by
    /// `CatalogProvider::lookup_property`); `StringId` is for general
    /// interned string content. v1.0 dynamic-schema fallback: a
    /// catalog impl MAY allocate a fresh `PropertyId` on first sight.
    ///
    /// Used by `arcgraph-query::semantic::catalog::CatalogProvider`
    /// (M4-21 binding pass) to resolve property references in
    /// `n.prop` access chains. Added by M4-21 (M4-02a) per ADR-038
    /// amendment-03 §TIER-1 GAP E + Structural-3.
    PropertyId
);
define_u32_id!(
    /// Local storage-partition identifier. The public engine accepts
    /// [`PartitionId::ZERO`] only.
    PartitionId
);

impl Default for PartitionId {
    // The public engine has one local storage partition.
    #[inline]
    fn default() -> Self {
        Self::ZERO
    }
}

// ---------- TenantId ----------
//
// TenantId is NOT generated by the macro because it has domain-specific
// named constants (SYSTEM / DEFAULT) rather than the generic ZERO / MAX
// sentinels, and the inner field is intentionally private to enforce
// construction through `new()` or the named consts.

/// Logical database (tenant) identifier. Every storage operation is scoped
/// to a tenant. See ADR-011 for the multi-tenancy design.
///
/// Reserved ranges (v1.0):
/// - `0` = [`Self::SYSTEM`] — system catalog, not accessible via user queries.
/// - `1` = [`Self::DEFAULT`] — the single default tenant for every v1.0 deployment.
/// - `2..=99` — reserved for future built-in tenants.
/// - `100+` — user-created tenants (assigned by M7 DDL layer).
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug, Serialize, Deserialize)]
#[repr(transparent)]
#[serde(transparent)]
pub struct TenantId(u64);

impl TenantId {
    /// System catalog tenant. Holds the tenant list, per-tenant schemas,
    /// RBAC subjects, and scope mappings. Not accessible via user queries.
    pub const SYSTEM: Self = Self(0);

    /// Default tenant used by every v1.0 deployment unless `USE DATABASE`
    /// is issued. DDL creates user tenants starting at ID 100 (M7).
    pub const DEFAULT: Self = Self(1);

    /// Construct from a raw u64. No validation in v1.0; range gating is
    /// added at the catalog layer in v1.1.
    #[inline]
    #[must_use]
    pub const fn new(raw: u64) -> Self {
        Self(raw)
    }

    /// Raw u64 representation for serialization and on-disk storage.
    #[inline]
    #[must_use]
    pub const fn raw(self) -> u64 {
        self.0
    }
}

impl From<u64> for TenantId {
    #[inline]
    fn from(v: u64) -> Self {
        Self(v)
    }
}

impl From<TenantId> for u64 {
    #[inline]
    fn from(v: TenantId) -> Self {
        v.0
    }
}

#[cfg(test)]
mod tests {
    use proptest::prelude::*;

    use super::*;

    #[test]
    fn zero_is_zero() {
        assert_eq!(PageId::ZERO.raw(), 0);
        assert_eq!(LabelId::ZERO.raw(), 0);
    }

    #[test]
    fn max_is_max() {
        assert_eq!(Lsn::MAX.raw(), u64::MAX);
        assert_eq!(TypeId::MAX.raw(), u32::MAX);
    }

    #[test]
    fn ordering_is_numeric() {
        assert!(PageId(1) < PageId(2));
        assert!(Lsn(5) > Lsn(4));
    }

    proptest! {
        #[test]
        fn page_id_u64_roundtrip(raw in any::<u64>()) {
            let id = PageId::new(raw);
            prop_assert_eq!(id.raw(), raw);
            prop_assert_eq!(PageId::from(raw), id);
            prop_assert_eq!(u64::from(id), raw);
        }

        #[test]
        fn node_id_u64_roundtrip(raw in any::<u64>()) {
            let id = NodeId::new(raw);
            prop_assert_eq!(id.raw(), raw);
        }

        #[test]
        fn rel_id_u64_roundtrip(raw in any::<u64>()) {
            let id = RelId::new(raw);
            prop_assert_eq!(id.raw(), raw);
        }

        #[test]
        fn lsn_u64_roundtrip(raw in any::<u64>()) {
            let lsn = Lsn::new(raw);
            prop_assert_eq!(lsn.raw(), raw);
        }

        #[test]
        fn label_id_u32_roundtrip(raw in any::<u32>()) {
            let id = LabelId::new(raw);
            prop_assert_eq!(id.raw(), raw);
            prop_assert_eq!(LabelId::from(raw), id);
            prop_assert_eq!(u32::from(id), raw);
        }

        #[test]
        fn type_id_u32_roundtrip(raw in any::<u32>()) {
            prop_assert_eq!(TypeId::new(raw).raw(), raw);
        }

        #[test]
        fn string_id_u32_roundtrip(raw in any::<u32>()) {
            prop_assert_eq!(StringId::new(raw).raw(), raw);
        }

        #[test]
        fn property_id_u32_roundtrip(raw in any::<u32>()) {
            let id = PropertyId::new(raw);
            prop_assert_eq!(id.raw(), raw);
            prop_assert_eq!(PropertyId::from(raw), id);
            prop_assert_eq!(u32::from(id), raw);
        }

        #[test]
        fn hashing_is_consistent(raw in any::<u64>()) {
            use std::collections::hash_map::DefaultHasher;
            use std::hash::{Hash, Hasher};
            let a = PageId::new(raw);
            let b = PageId::new(raw);
            let mut ha = DefaultHasher::new();
            let mut hb = DefaultHasher::new();
            a.hash(&mut ha);
            b.hash(&mut hb);
            prop_assert_eq!(ha.finish(), hb.finish());
        }

        #[test]
        fn total_order_matches_u64(a in any::<u64>(), b in any::<u64>(), c in any::<u64>()) {
            // Every ID newtype must expose a total order identical to the
            // underlying u64. Trichotomy holds; transitivity holds.
            let (ia, ib, ic) = (PageId::new(a), PageId::new(b), PageId::new(c));
            prop_assert_eq!(ia.cmp(&ib), a.cmp(&b));
            if ia < ib && ib < ic {
                prop_assert!(ia < ic, "order must be transitive");
            }
            let lt = u8::from(ia < ib);
            let eq = u8::from(ia == ib);
            let gt = u8::from(ia > ib);
            prop_assert_eq!(lt + eq + gt, 1u8);
        }

        #[test]
        fn ids_sort_numerically(raws in prop::collection::vec(any::<u64>(), 0..=32)) {
            let mut ids: Vec<PageId> = raws.iter().copied().map(PageId::new).collect();
            ids.sort();
            let mut expected = raws.clone();
            expected.sort();
            let got: Vec<u64> = ids.iter().map(|p| p.raw()).collect();
            prop_assert_eq!(got, expected);
        }

        #[test]
        fn tenant_id_roundtrip(raw in any::<u64>()) {
            let t = TenantId::new(raw);
            prop_assert_eq!(t.raw(), raw);
            prop_assert_eq!(TenantId::from(raw), t);
            prop_assert_eq!(u64::from(t), raw);
        }
    }

    // ---- TenantId domain constants ----

    #[test]
    fn tenant_id_system_is_zero() {
        assert_eq!(TenantId::SYSTEM.raw(), 0);
    }

    #[test]
    fn tenant_id_default_is_one() {
        assert_eq!(TenantId::DEFAULT.raw(), 1);
    }

    #[test]
    fn tenant_id_system_lt_default() {
        assert!(TenantId::SYSTEM < TenantId::DEFAULT);
    }

    #[test]
    fn tenant_id_new_roundtrip_edge_cases() {
        assert_eq!(TenantId::new(0), TenantId::SYSTEM);
        assert_eq!(TenantId::new(1), TenantId::DEFAULT);
        assert_eq!(TenantId::new(u64::MAX).raw(), u64::MAX);
        assert_eq!(TenantId::new(u64::MAX - 1).raw(), u64::MAX - 1);
    }

    // ---- PartitionId ----

    #[test]
    fn partition_id_zero_is_zero() {
        assert_eq!(PartitionId::ZERO.raw(), 0);
    }

    #[test]
    fn partition_id_default_is_zero() {
        // The local storage partition defaults to zero.
        let p = PartitionId::default();
        assert_eq!(p, PartitionId::ZERO);
    }

    #[test]
    fn partition_id_u32_roundtrip() {
        let p = PartitionId::new(42);
        assert_eq!(p.raw(), 42);
        assert_eq!(PartitionId::from(42u32), p);
        assert_eq!(u32::from(p), 42);
    }

    #[test]
    fn partition_id_ordering_is_numeric() {
        assert!(PartitionId(1) < PartitionId(2));
    }
}
